# Generated by Django 5.0.1 on 2024-02-03 18:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='saving_goal',
            field=models.DecimalField(decimal_places=2, default=None, help_text='Enter Percentage Between 0 and 100', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
