# Generated by Django 5.0.1 on 2024-02-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='customer',
            name='username',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
