# Generated by Django 5.0.1 on 2024-02-26 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_customer_email_customer_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profileimg',
            field=models.ImageField(default='static/assets/logo.png', upload_to='media'),
        ),
    ]
