# Generated by Django 5.0.1 on 2024-02-26 22:22

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_userexpenserecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='income_sources',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 2, 26, 22, 21, 53, 570660, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='income_sources',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='monthly_expense',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthly_expense',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
