# Generated by Django 5.0.1 on 2024-03-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_customer_age_customer_location_alter_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='info',
            field=models.TextField(default='This is my about section'),
        ),
    ]
